[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aiapp"
version = "0.1.0"
description = "AI App project"
dependencies = [
    "pandas",
    "numpy",
    "matplotlib",
    "ipykernel",
    "pandas-stubs~=2.3.3",
]
requires-python = ">=3.10"
